In [1]:
import numpy as np
import pandas as pd
import matplotlib_inline as plt
from sklearn.linear_model import LinearRegression
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
x_df = df.drop(['price'],axis=1)
x_df


area
0  2600
1  3000
2  3200
3  3600
4  4000

In [5]:
y_df=df['price']
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [6]:
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [7]:
lr.coef_

array([135.78767123])

In [8]:
lr.intercept_

180616.43835616432

In [9]:
import pickle

In [18]:
with open("lr_model",'wb') as file:
    pickle.dump(lr,file)

In [19]:
with open("lr_model",'rb') as file:
    mp = pickle.load(file)

In [20]:
mp.coef_

array([135.78767123])

In [21]:
mp.predict([[5000]])

array([859554.79452055])

In [22]:
import json


samplejson = {
     "name" : "luminar",
     "place" : "Kochi",
     "phonenumber":"8714135828"

}
json_object = json.dumps(samplejson)

In [23]:
with open("sample.json","w") as file:
    file.write(json_object)

In [24]:
with open("sample.json","r") as file:
    newdata = json.load(file)

In [17]:
newdata

{'name': 'luminar', 'place': 'Kochi', 'phonenumber': '8714135828'}

In [25]:
import joblib

In [26]:
joblib.dump(lr,'model_joblib_new')

['model_joblib_new']

In [27]:
mj = joblib.load('model_joblib_new')

In [28]:
mj

LinearRegression()

In [29]:
mj.coef_

array([135.78767123])

In [30]:
mj.intercept_

180616.43835616432

In [32]:
mj.predict

<bound method LinearModel.predict of LinearRegression()>

In [33]:
joblib.load('lr_model')

LinearRegression()