In [1]:
#install python package



In [2]:
##pip install numpy

import numpy

In [3]:
import numpy as np

In [4]:
myList=[1,2,3,4,5]
stringList = ["apple","orange"]

In [5]:
print(myList)
print(stringList)

[1, 2, 3, 4, 5]
['apple', 'orange']


In [6]:
print(type(myList))

<class 'list'>


In [7]:
#dir(np)

In [8]:
#help(np)

In [9]:
arr = np.array(myList)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#Shape and Size
arr.shape


(5,)

In [12]:
arr.size

5

In [13]:
my_list1=[1,2,3,4]
my_list2=[2,4,6,8]
my_list3=[3,5,7,9]
arr1 = np.array([my_list1,my_list2,my_list3])

In [14]:
 type(arr1)

numpy.ndarray

In [15]:
arr1.shape

(3, 4)

In [16]:
arr1.size

12

In [17]:
arr1

array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 5, 7, 9]])

In [18]:
arr


array([1, 2, 3, 4, 5])

In [19]:
my_list1=([[1,2,3,4,5],[2,3,4,5,6],[4,5,6,7,8],[3,4,5,2,12],[34,35,43,21,22]])
arr1 = np.array(my_list1)
print("priting the variable",arr1,"\n")
print("printing the size of the array",arr1.size,"\n")
print("printing the type of an array",type(arr1),"\n")
print("printing the shape of the array",arr1.shape,"\n")
print("printing the 2nd row and 3rd column",arr1[1,2],"\n")

print("printing the 1st row and 4th column",arr1[0,3],"\n")
print("printing the 5st row and 3th column",arr1[4,2],"\n")

priting the variable [[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 3  4  5  2 12]
 [34 35 43 21 22]] 

printing the size of the array 25 

printing the type of an array <class 'numpy.ndarray'> 

printing the shape of the array (5, 5) 

printing the 2nd row and 3rd column 4 

printing the 1st row and 4th column 4 

printing the 5st row and 3th column 43 



In [20]:
print(arr1)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 3  4  5  2 12]
 [34 35 43 21 22]]


In [21]:
# Negative Indexing

In [22]:
my_list = ([2,4,6,8,10],[3,5,7,23,13])
arr1 = np.array(my_list)
print(arr1)

[[ 2  4  6  8 10]
 [ 3  5  7 23 13]]


In [23]:
arr1[1,-1]

13

In [24]:
arr1[1,-3]

7

In [25]:
arr1[0,-2]

8

In [26]:
# Numpy Array Slicing 1D
# Taking an element from one given indexing to another given index

In [27]:
my_list = [1,2,3,4,5,6,7,8,9,10]
arr1 = np.array(my_list)
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
arr1[0:6]

array([1, 2, 3, 4, 5, 6])

In [29]:
arr1[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [30]:
arr1[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr1[-3:-1]

array([8, 9])

In [32]:
arr1[1:3]

array([2, 3])

In [33]:
arr1[1::3]

array([2, 5, 8])

In [34]:
array[::2]

NameError: name 'array' is not defined

In [ ]:
arr1[::2]

In [ ]:
arr1[::]

In [ ]:
arr1[3::2]

In [ ]:
my_list1=([[1,2,3,4,5],[11,12,13,14,15],[24,25,26,27,28],[33,34,35,32,38],[44,45,43,41,42]])
arr1 = np.array(my_list1)
print(arr1)

In [ ]:
arr1[:,1:4]

In [ ]:
arr1[2:3,1:4]

In [ ]:
arr1[2:3,2:3]

In [ ]:
arr1[2:4,1:3]

In [ ]:
arr1[1:3,1:3]

In [ ]:
#Arange Function


In [ ]:
np.arange(10)

In [ ]:
np.arange(20)

In [ ]:
np.arange(2,15)

In [ ]:
np.arange(4,21)

In [ ]:
np.arange(3,11)

In [ ]:
np.arange(1,21,2)

In [ ]:
#linspace 
np.linspace(0,100)

# Numpy Data Types


In [ ]:
arr1 = np.array(["banana","cherry","strawberry"])
print(arr1.dtype)

In [41]:
arr2 = np.array([1,2,3,4,5],dtype=np.int64)
print(arr2)
print(arr2.dtype)

[1 2 3 4 5]
int64


In [43]:
arr2 = np.array([1,2,3,4,5],dtype=np.float64)
print(arr2)
print(arr2.dtype)

[1. 2. 3. 4. 5.]
float64


In [57]:
x = np.array([[1,2],[4,5]],dtype=np.int64)
y = np.array([[3,4],[5,1]],dtype = np.int64)
print(x)
print("**")
print(y)

[[1 2]
 [4 5]]
**
[[3 4]
 [5 1]]


In [58]:
x+y

array([[4, 6],
       [9, 6]])

In [59]:
np.add(x,y)

array([[4, 6],
       [9, 6]])

In [60]:
np.subtract(x,y)

array([[-2, -2],
       [-1,  4]])

In [61]:
np.divide(x,y)

array([[0.33333333, 0.5       ],
       [0.8       , 5.        ]])

In [62]:
np.multiply(x,y)

array([[ 3,  8],
       [20,  5]])

In [63]:
x/y

array([[0.33333333, 0.5       ],
       [0.8       , 5.        ]])

In [64]:
np.exp(x)

array([[  2.71828183,   7.3890561 ],
       [ 54.59815003, 148.4131591 ]])

In [65]:
np.log(x)

array([[0.        , 0.69314718],
       [1.38629436, 1.60943791]])

In [66]:
np.floor(x)

array([[1., 2.],
       [4., 5.]])

In [67]:
np.round(x)

array([[1, 2],
       [4, 5]])

In [68]:
np.ceil(x)

array([[1., 2.],
       [4., 5.]])

In [90]:
x = np.array([[1,2,3],[4,5,1]],dtype=np.int64)
y = np.array([[3,4,1],[5,1,2]],dtype = np.int64)
z = np.array([[1,2,2],[3,5,1]],dtype=np.int64)
print(x,y,z)

[[1 2 3]
 [4 5 1]] [[3 4 1]
 [5 1 2]] [[1 2 2]
 [3 5 1]]


In [91]:
np.multiply(x,y,z)

array([[ 3,  8,  3],
       [20,  5,  2]])

In [92]:
x*y*z

array([[  9,  64,   9],
       [400,  25,   4]])

In [93]:
a = np.multiply(x,y)
print(a)

[[ 3  8  3]
 [20  5  2]]


In [94]:

b = np.multiply(z,a)
print(b)

[[  9  64   9]
 [400  25   4]]


In [100]:
np.dot(x,y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [175]:
x

array([  1,  34, 200,   4,   5])

In [176]:
x.shape

(5,)

In [177]:
np.sum(x)

244

In [178]:
np.sum(x,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [181]:
y

array([[3, 4, 1],
       [5, 1, 2]])

In [182]:
np.sum(y,axis=0) #column sum

array([8, 5, 3])

In [183]:
x

array([  1,  34, 200,   4,   5])

In [184]:

np.sum(y,axis=1) # row sum

array([8, 8])

In [114]:
y

array([[3, 4, 1],
       [5, 1, 2]])

In [115]:
x.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 1, 8]])

In [116]:
x


array([[1, 2, 3],
       [4, 5, 1],
       [6, 7, 8]])

In [117]:
x.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 1, 8]])

In [118]:
x = np.array([[1,2,3],[4,5,1],[6,7,8]],dtype=np.int64)
print(x)

[[1 2 3]
 [4 5 1]
 [6 7 8]]


In [119]:
x.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 1, 8]])

# Numpy array copy Vs View

In [188]:
arr = np.array([1,2,3,4,5,])

In [189]:
x = arr

In [190]:
print(x)

[1 2 3 4 5]


In [191]:
arr

array([1, 2, 3, 4, 5])

In [125]:
print(arr)

[1 2 3 4 5]


In [192]:
x[0] = 100
print(x)

[100   2   3   4   5]


In [127]:
print(arr)

[100   2   3   4   5]


In [128]:
x[3] = 400

In [129]:
print(x)

[100   2   3 400   5]


In [130]:
print(arr)

[100   2   3 400   5]


In [131]:
arr = np.array([1,2,3,4,5,])
x = arr.copy()

In [132]:
x[2] = 200
print(x)

[  1   2 200   4   5]


In [133]:
print(arr)

[1 2 3 4 5]


In [134]:
x[1]=34
print(x)

[  1  34 200   4   5]


In [135]:
print(arr)

[1 2 3 4 5]


# Numpy Array Reshaping

In [155]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])


In [146]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:

np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [148]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [149]:
arr.shape

(10,)

In [157]:
arr = np.arange(2,13)
print(arr)
arr.shape


[ 2  3  4  5  6  7  8  9 10 11 12]


(11,)

In [158]:
arr.reshape(2,2)


ValueError: cannot reshape array of size 11 into shape (2,2)

In [195]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])

In [196]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [197]:
arr.shape

(18,)

In [198]:
arr.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

# Flattering the arrays
# 2D------->3D

In [199]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

# Iterating Array

In [211]:
arr1 = np.arange(1,7).reshape(3,2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [212]:
for x in arr1:
    print(x)
    

[1 2]
[3 4]
[5 6]


# Joining Numby Arrays

In [213]:
arr1 = np.array([1,2,3,])
arr2 = np.array([4,5,6])

In [215]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [217]:
arr1 = np.array([[1,2,],[3,4]])
arr2 = np.array([[4,5],[6,7]])

In [220]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

In [222]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])